project_id = "klltuuwzedbhkbykayyn"

[functions.resolve-phone]
verify_jwt = false

[functions.create-employee]
verify_jwt = false

[functions.update-employee]
verify_jwt = false

[functions.migrate-to-phone]
verify_jwt = false
